#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


str_repl="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 http:/dev-israel.tech;\n\t}"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -e "s|server_name _;|$str_repl|" /etc/nginx/sites-enabled/default

sudo service nginx start
