#!/usr/bin/env bash
#a script for 404

# Install NGINX
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom 404 page
sudo mkdir -p /var/www/html
sudo tee /var/www/html/custom_404.html <<EOL
Ceci n'est pas une page
EOL

# Configure NGINX for custom 404 page
sudo tee /etc/nginx/sites-available/default <<EOL
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 http://dev-israel.tech;
        }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /custom_404.html;
        }

        location = /custom_404.html {
                internal;
                root /var/www/html;
        }
}
EOL

# Test NGINX configuration and reload
sudo service nginx start
