#!/bin/bash
#a script for 404

sudo apt-get -y update
sudo apt-get -y install nginx

mystr="@oui_oui_baguette;\n\t}\n\n\tlocation @oui_oui_baguette {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n\'est pas une page\";"

sudo sed -i -z "s|"=404;"|$mystr|" /etc/nginx/sites-enabled/default

sudo service nginx restart
