#!/usr/bin/env bash
# Script that make nginx listen to port 80
rm /etc/nginx/sites-enabled/default
sed -i s/8080/80/ /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
