#!/usr/bin/env bash
#A script that configures an Ubuntu
# server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

file=~/hosts.new
cp /etc/hosts $file

a=1
b=2
sed -i -e "${a}a\\
127.0.0.2\t127.0.0.1" "$file"
#sed -i -e "${a}\\n127.0.0.2\t127.0.0.1" $file

sed -i -e "${b}a\\
8.8.8.8\tfacebook.com" "$file"

cp -f $file /etc/hosts

