#!/usr/bin/env bash
#A script that configures an Ubuntu
# server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

file=~/hosts.new
cp /etc/hosts $file

sed -i '/^127.0.0.2 localhost$/c\127.0.0.2 localhost' "$file"

# Update facebook.com resolution (if exists)
sed -i '/^8.8.8.8 facebook.com$/c\8.8.8.8 facebook.com' "$file"

#sed -i -e "s\\n127.0.0.2\t127.0.0.1" $file
#sed -i -e "s\\n8.8.8.8\tfacebook.com\n" $file

cp -f $file /etc/hosts

